### ISSUE TITLE
ValueError: Error initialising UART

### ISSUE THREAD

**Issue by Jianfengusa** [eclipse-mraa/mraa#1001]
Having trouble initialising UART on Ubuntu 16.04.
Traceback (most recent call last):
  File "gps.py", line 10, in <module>
    u = mraa.Uart(gps_port)
  File "/usr/lib/python3.5/dist-packages/mraa.py", line 1073, in __init__
    this = _mraa.new_Uart(*args)
ValueError: Error initialising UART

my systemlog is 
Mar 21 15:12:01 irrigationgps-16 libmraa[10208]: libmraa version v2.0.0 initialised by user 'irrigation-gps-16' with EUID 1000
Mar 21 15:12:01 irrigationgps-16 libmraa[10208]: Adding i2c bus found on i2c-5 on adapter i2c_designware.1
Mar 21 15:12:01 irrigationgps-16 libmraa[10208]: Adding i2c bus found on i2c-4 on adapter i2c_designware.0
Mar 21 15:12:01 irrigationgps-16 libmraa[10208]: up2: kernel pinctrl driver unavailable
Mar 21 15:12:01 irrigationgps-16 libmraa[10208]: up2: Platform failed to initialise
Mar 21 15:12:01 irrigationgps-16 libmraa[10208]: imraa: Failed to open lock file
Mar 21 15:12:01 irrigationgps-16 libmraa[10208]: gpio: platform doesn't support chardev, falling back to sysfs
Mar 21 15:12:01 irrigationgps-16 libmraa[10208]: libmraa initialised for platform 'Unknown platform' of type 98
Mar 21 15:12:01 irrigationgps-16 libmraa[10208]: uart: open(/dev/ttyS5) failed: Permission denied
Mar 21 15:12:12 irrigationgps-16 org.gnome.zeitgeist.SimpleIndexer[964]: ** (zeitgeist-fts:1721): WARNING **: Unable to get info on application://nautilus-autostart.desktop

**Comment by Propanu** [comment]
Hi @Jianfengusa, it looks like a permission issue. You need to either run your application as the super user (with `sudo`) or enable I/O access for the regular user by following [these](https://wiki.up-community.org/Ubuntu#Enable_the_HAT_functionality_from_userspace_2) instructions from Aaeon for the UP2 board. Thanks!
