### ISSUE TITLE
Error in Rock Pi E

### ISSUE THREAD

**Issue by Ataraxiall** [eclipse-mraa/mraa#1038]
Good,

I'm trying to install it on a rock pi e that has official mraa libraries.

, but I get this error.
`make: *** [mraa.target.mk:139: Release/obj.target/mraa/src/mraa.o] Error 1
make: se sale del directorio '/root/.node-red/node_modules/mraa/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 5.8.14-rockchip64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.node-red/node_modules/mraa
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Linux 5.8.14-rockchip64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mraa"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! mraa@1.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mraa@1.9.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mraa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mraa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mraa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.node-red/npm-debug.log`

any idea what might be happening? Thank you all!

**Comment by Ataraxiall** [comment]
trying 0, now the error is this ...
 CC(target) Release/obj.target/mraa/src/spi/spi.o
  CC(target) Release/obj.target/mraa/src/pwm/pwm.o
  CC(target) Release/obj.target/mraa/src/i2c/i2c.o
  CC(target) Release/obj.target/mraa/src/gpio/gpio.o
  CC(target) Release/obj.target/mraa/src/mraa.o
../src/mraa.c: In function ‘imraa_init’:
../src/mraa.c:157:2: error: #error mraa_ARCH NOTHING
 #error mraa_ARCH NOTHING
  ^~~~~
make: *** [mraa.target.mk:148: Release/obj.target/mraa/src/mraa.o] Error 1
make: se sale del directorio '/root/node_modules/mraa/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.8.16-rockchip64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/mraa
gyp ERR! node -v v10.22.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mraa@1.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mraa@1.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-20T14_02_33_577Z-debug.log
``
