### ISSUE TITLE
Error when running an app using node command

### ISSUE THREAD

**Issue by vijvcic** [eclipse-mraa/mraa#967]
Hello guys, i'm having  an error when i'm running my application with node command

```
root@edison:~# node intruderAlert.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'mraa'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/root/intruderAlert.js:2:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

my nodejs version is  8.11.3
Could anyone help me to resolve this problem  ? . I was thinking it because my nodejs version is > v6 so it cause the error when running the app

**Comment by Propanu** [comment]
Hi @vijvcic, you might have to compile mraa from source with a custom version of swig for node 8 support. Please refer to the documentation [here](https://github.com/intel-iot-devkit/mraa/blob/master/docs/building.md#dependencies-continued) and let us know if you have further questions.
